### ISSUE TITLE
レビュー用Issue

### ISSUE THREAD

**Issue by Hanason01** [Hanason01/JamMy.dev#38]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。

- 録音した短い音声を組み合わせて、誰でも簡単に仲間とコラボ作品を創れるCGM型の音声合成サービスです。アイデアを集結させてオリジナルソングや曲を作ったり、ノリで創る笑えるモノまで、自己表現を組み合わせて唯一無二のコラボ作品を創り、世界へ発信できます。

- サービスの根幹となる部分は、「録音音声の合成」です。あるユーザーが録音し投稿（Project）し、それに対し別のユーザーが同様に録音して応募（Request）を行う、そして投稿主が応募管理・音声合成（Manegement）を行い一つの音声ファイルに統合します。

- それらの作品をユーザー同士で共有させたり、より多くのコラボ作品が生まれるようにする為に、この根幹となる機能をCGM機能で拡張していくものです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：35時間

■ProjectsのURL
https://github.com/users/Hanason01/projects/2

■MVPリリースまで
- [ ] 環境構築
- [ ] デプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] 投稿一覧機能（ProjectIndex）
- [ ] 投稿機能（録音、編集、投稿）（ProjectPost）
- [ ] 応募機能（録音、編集、応募）（ProjectRequest）
- [ ] 応募管理機能（編集、音声合成、保存）（ProjectManegement）
- [ ] 単体テスト（UnitTest）
- [ ] 統合テスト（IntegrationTest）

■MVP後
- [ ] Google認証登録機能
- [ ] パスワードリセット機能
- [ ] ブックマーク機能
- [ ] いいね機能
- [ ] コメント機能（投稿に対するコメントとコメントに対するコメント、いいね）
- [ ] ハッシュタグ機能
- [ ] カテゴリー機能（投稿一覧画面にてフィルタリング）
- [ ] 共有機能（URL、Xへの投稿）
- [ ] ユーザーページ機能（他者ユーザーページ閲覧）
- [ ] マイページ機能
- [ ] プロフィール機能
- [ ] フォロー機能
- [ ] 通知機能（フィード、応募、フォロー）
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] 使い方説明更新
- [ ] CI（GitHubActions）
- [ ] 独自ドメイン取得
- [ ] レスポンシブ対応
- [ ] 単体テスト
- [ ] 統合テスト

■MVPレビュー依頼予定日
予定日：2024年 11月 26日

**Comment by TakenakaEri** [comment]
LGTMです！
もし、ご自身で必要だと思ったissueは随時追加していただいてもんだいありません〜！

この後も頑張ってくださいね！！

**Comment by Hanason01** [comment]
ありがとうございます！
承知しました。今後ともよろしくお願いいたします。
