### ISSUE TITLE
MPVレビュー用Issue

### ISSUE THREAD

**Issue by Hanason01** [Hanason01/JamMy.dev#89]
## 各種情報
サービス名：JamMy
サービスURL：https://www.jam-my.com/
サービス概要：音声を投稿し、気軽にコラボ作品を作れるアプリ

## MVPで検証する事項
- [ ] ユーザー新規登録ができる
- [ ] ユーザーログイン、ログアウトができる。ログイン保持ができる
- [ ] 投稿一覧ページで投稿が見れる、投稿音声の再生ができる
- [ ] 投稿画面（BottomNaviの「＋」よりリンク）で録音、投稿ができる
- [ ] 投稿一覧ページで投稿した内容を確認できる

## READMEレビュー時にMVPリリース時点で実装予定だった機能
 - [ ] トップページ
 - [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] 投稿一覧機能（ProjectIndex）
- [ ] 投稿機能（録音、編集、投稿）（ProjectPost）
- [ ] 応募機能（録音、編集、応募）（ProjectRequest）
- [ ] 応募管理機能（編集、音声合成、保存）（ProjectManegement）
- [ ] 単体テスト（UnitTest）
- [ ] 統合テスト（IntegrationTest）

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください。なければこの項目は省略してください。
- [ ] 応募機能（録音、編集、応募）（ProjectRequest）
- [ ] 応募管理機能（編集、音声合成、保存）（ProjectManegement）
- [ ] 単体テスト（UnitTest）
- [ ] 統合テスト（IntegrationTest）

「ユーザー同士の交流」に関する機能は本リリースにて行う事とした為、応募、応募管理は本リリースにて実装します。
また音声の編集については、現時点では必須ではない為本リリースで対応します。
テストについては、本リリースにて対応します。

## サービスイメージがわかるようなスクリーンショット等
![使用イメージ](https://github.com/user-attachments/assets/756baa87-b90b-4029-80fc-69fae044f5ff)

一連の流れ
「TopPage」→
「投稿を見る or　ログインする（アイコンボタンからでも遷移」→
「ログイン or　新規登録」→
「投稿一覧へ遷移」→
「BottomNaviの「＋」で投稿画面へ」→
「録音設定を行い、録音ボタンで録音処理」→
「プレビュー画面で確認、取り直す場合は「Xボタン押下」→
「投稿画面でタイトルと概要を入力して投稿するボタン押下→投稿一覧画面へ遷移」→
「投稿一覧画面にて投稿を確認」→
「投稿の再生ボタンを押すと、画面下部に再生コントローラーが表示される」

**Comment by kenchasonakai** [comment]
認証に失敗しましたとなり投稿が出来ないようです
ご確認をお願いします
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/1659f067017dc0b09e3af84b866bb908.png)](https://startup-technology.gyazo.com/1659f067017dc0b09e3af84b866bb908)

**Comment by Hanason01** [comment]
フィードバックありがとうございます。
認証エラーに対応いたしましたので、再度確認をお願いできますでしょうか？

**Comment by kenchasonakai** [comment]
LGTMです！

**Comment by Hanason01** [comment]
ありがとうございます！今後ともどうぞよろしくお願いいたします。
